stages:
#  - release
  - deploy

#release-prod-job:
#  image: docker:19.03.12
#  services:
#    - docker:19.03.12-dind
#  stage: release
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#  only:
#    - main



deploy-prod-job:
  stage: deploy
  before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh -o StrictHostKeyChecking=no root@$VPS_DEPLOY "cd /root/botcoin && mv ./bot/.env ./"
    - ssh -o StrictHostKeyChecking=no root@$VPS_DEPLOY "cd /root/botcoin && rm -rf ./bot"
    - ssh -o StrictHostKeyChecking=no root@$VPS_DEPLOY "cd /root/botcoin/ && git clone https://github.com/DavidFFDAW/Botcoin-discord-bot.git bot"
    - ssh -o StrictHostKeyChecking=no root@$VPS_DEPLOY "cd /root/botcoin && mv ./.env ./bot"
    - ssh -o StrictHostKeyChecking=no root@$VPS_DEPLOY "cd /root/botcoin/bot && docker image rm -f botcoin-img && docker build -t botcoin-img ."
    - ssh -o StrictHostKeyChecking=no root@$VPS_DEPLOY "cd /root/botcoin/bot && docker container rm -f botcoin-container && docker run --name botcoin-container -d botcoin-img"
  only:
    - main